apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: da
type: Opaque
stringData:
  # MongoDB Atlas connection
  DATABASE_URL: "mongodb+srv://aadi:B69NSfHoaZxVxoRY@aadi-play.nbzycdh.mongodb.net/devops-assignment"
  
  # JWT & Auth secrets
  JWT_SECRET: "abcdefgh"
  NEXTAUTH_SECRET: "abcdefgh"
  
  # NextAuth URL (use ingress hostname or external URL)
  NEXTAUTH_URL: "http://nextjs-app.local"
  
  # App configuration
  NODE_ENV: "production"
  PORT: "3000"
